GET http://localhost:3002/courses
# Used to recover all the courses on the database

###

POST http://localhost:3002/courses
# Used to sore a Course on the database
Content-Type: application/json

{
    "title": "Aula da Raissa 01",
    "teacher": "3",
    "price": "400",
    "location": "Location da Aula",
    "dateStart": "2020-01-01",
    "dateEnd": "2020-01-01",
    "hourStart": "08:00",
    "hourEnd": "12:00",
    "interval": "Sábados e Domingos",
    "description": "Utilizando sua vasta experiência em Dança do Ventre, Nadja propõe workshop técnico em movimentação de quadril para Tribal Fusion baseado em técnicas “baladi” egípcias.",
    "inscriptionUrl": "www.youtube.com",
    "classUrl": "www.youtube.com"
}

###
