GET http://localhost:3002/users

###

GET http://localhost:3002/users/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjAzMzIwNjMyfQ.wh6ootzIFDylZgP6W87d3M14y9UfYIZ4JKApz1OTCqU
id: 3

###

POST http://localhost:3002/users
content-type: application/json

    {
        "username": "raisa.latorraca",
        "fullname": "Raisa Latorraca",
        "password": "raisalatorraca",
        "level": "admin"
    }

###

POST http://localhost:3002/login
# Used to login
Content-Type: application/json

    {
        "username":"ivan.zanon",
        "password":"ivanzanon"
    }

###

DELETE http://localhost:3002/users/2